### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by samuong** [samuong/alpaca#9]
A long-running Alpaca session ended up not being able to proxy traffic, and had the following error messages in the logs:

```
2019/06/03 09:15:53 server.go:2979: http: Accept error: accept tcp 127.0.0.1:3128: accept: too many open files; retrying in 5ms
2019/06/03 09:15:55 server.go:2979: http: Accept error: accept tcp 127.0.0.1:3128: accept: too many open files; retrying in 10ms
2019/06/03 09:15:55 server.go:2979: http: Accept error: accept tcp 127.0.0.1:3128: accept: too many open files; retrying in 20ms
2019/06/03 09:15:55 server.go:2979: http: Accept error: accept tcp 127.0.0.1:3128: accept: too many open files; retrying in 40ms
2019/06/03 09:15:55 server.go:2979: http: Accept error: accept tcp 127.0.0.1:3128: accept: too many open files; retrying in 80ms
```

It looks like Alpaca is leaking connections, maybe due to not closing one half of the CONNECT requests (ref [ProxyHandler.handleConnect](https://github.com/samuong/alpaca/blob/master/proxy.go#L83)).

In addition to fixing the leak, there should be better visibility into what's going on in terms of open connections.

**Comment by samuong** [comment]
This should be fixed by 0904ccc. I've been running with this change locally for a few days now, and it appears to clean up all the leaked file descriptors.

In case it's useful in the future, the number of open connections (in each direction of a CONNECT tunnel) can be found using something like `lsof -Pn -c alpaca | awk '!/ESTABLISHED/{next} /:3128/{proxy++;next} {tunnel++} END{printf "%d (proxy) %d (tunnel)\n", proxy, tunnel}'`.

**Comment by ferrieux** [comment]
Hi, 6 years and a half down the road, the problem is back :P
This is the Debian Trixie package `2.0.11+0012.44800649.25857702.ci1`.

I've done some logging to understand the onset:
  - periodically doing "netstat -nap | grep -w $ALPACA_PID"
  - capturing all network traffic on loopback (as the leaked connections are all local)

Here is what I found:

  1. The onset is sudden: below are snapshots at 17:02:15 and 17:02:25; the first has 22 sockets, the second has 4046 of them.
  2. All the leaked sockets appear to have both endpoints in the alpaca process (it connects to itself)
  3. Looking at the packet capture, all those connections are initiated within 3 seconds (17:02:17->17:02:20) and start with a CONNECT to mtalk.google.com:

       ```shell
       CONNECT.mtalk.google.com:5228.HTTP/1.1..Host:.mtalk.google.com:5228..User-Agent:.Go-http-client/1.1..Proxy-Connection:.keep-alive....
       ```
   4. The trigger is probably a single periodic CONNECT event from a Chrome browser that I left open


```shell
20260212_170215.464          1  tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      26983/alpaca        
20260212_170215.464          2  tcp        0      0 10.134.97.231:53766     10.171.108.193:8080     ESTABLISHED 26983/alpaca        
20260212_170215.464          3  tcp        0      0 10.134.97.231:51940     10.171.108.193:8080     ESTABLISHED 26983/alpaca        
20260212_170215.464          4  tcp        0      0 10.134.97.231:38228     10.171.108.193:8080     ESTABLISHED 26983/alpaca        
20260212_170215.464          5  tcp        0      0 10.134.97.231:59692     10.171.108.81:8080      ESTABLISHED 26983/alpaca        
20260212_170215.464          6  tcp        0      0 10.134.97.231:38220     10.171.108.193:8080     ESTABLISHED 26983/alpaca        
20260212_170215.464          7  tcp        0      0 10.134.97.231:38236     10.171.108.193:8080     ESTABLISHED 26983/alpaca        
20260212_170215.464          8  tcp        0      0 10.134.97.231:53620     10.171.108.193:8080     ESTABLISHED 26983/alpaca        
20260212_170215.464          9  tcp        0      0 10.134.97.231:53694     10.171.108.193:8080     ESTABLISHED 26983/alpaca        
20260212_170215.464         10  tcp        0      0 10.134.97.231:53808     10.171.108.193:8080     ESTABLISHED 26983/alpaca        
20260212_170215.464         11  tcp        0      0 10.134.97.231:53686     10.171.108.193:8080     ESTABLISHED 26983/alpaca        
20260212_170215.464         12  tcp        0      0 10.134.97.231:38248     10.171.108.193:8080     ESTABLISHED 26983/alpaca        
20260212_170215.464         13  tcp6       0      0 ::1:8080                :::*                    LISTEN      26983/alpaca        
20260212_170215.464         14  tcp6       0      0 ::1:8080                ::1:53072               ESTABLISHED 26983/alpaca        
20260212_170215.464         15  tcp6       0      0 ::1:8080                ::1:50034               ESTABLISHED 26983/alpaca        
20260212_170215.464         16  tcp6       0      0 ::1:8080                ::1:53098               ESTABLISHED 26983/alpaca        
20260212_170215.464         17  tcp6       0      0 ::1:8080                ::1:56916               ESTABLISHED 26983/alpaca        
20260212_170215.464         18  tcp6       0      0 ::1:8080                ::1:56924               ESTABLISHED 26983/alpaca        
20260212_170215.464         19  tcp6       0      0 ::1:8080                ::1:52984               ESTABLISHED 26983/alpaca        
20260212_170215.464         20  tcp6       0      0 ::1:8080                ::1:50042               ESTABLISHED 26983/alpaca        
20260212_170215.464         21  tcp6       0      0 ::1:8080                ::1:50040               ESTABLISHED 26983/alpaca        
20260212_170215.464         22  tcp6       0      0 ::1:8080                ::1:50054               ESTABLISHED 26983/alpaca        
20260212_170215.465     
20260212_170225.549          1  tcp        1      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      26983/alpaca        
20260212_170225.549          2  tcp        0      0 127.0.0.1:53488         127.0.0.1:8080          ESTABLISHED 26983/alpaca        
20260212_170225.549          3  tcp        0      0 127.0.0.1:57400         127.0.0.1:8080          ESTABLISHED 26983/alpaca        
20260212_170225.549          4  tcp        0      0 127.0.0.1:34406         127.0.0.1:8080          ESTABLISHED 26983/alpaca        
20260212_170225.549          5  tcp        0      0 127.0.0.1:8080          127.0.0.1:38844         ESTABLISHED 26983/alpaca        
20260212_170225.549          6  tcp        0      0 127.0.0.1:8080          127.0.0.1:35456         ESTABLISHED 26983/alpaca        
20260212_170225.549          7  tcp        0      0 127.0.0.1:33532         127.0.0.1:8080          ESTABLISHED 26983/alpaca        
20260212_170225.549          8  tcp        0      0 127.0.0.1:35376         127.0.0.1:8080          ESTABLISHED 26983/alpaca        
20260212_170225.549          9  tcp        0      0 127.0.0.1:8080          127.0.0.1:33234         ESTABLISHED 26983/alpaca        
...
20260212_170225.587       4028  tcp        0      0 127.0.0.1:8080          127.0.0.1:39728         ESTABLISHED 26983/alpaca        
20260212_170225.587       4029  tcp        0      0 127.0.0.1:8080          127.0.0.1:35438         ESTABLISHED 26983/alpaca        
20260212_170225.587       4030  tcp        0      0 127.0.0.1:8080          127.0.0.1:59002         ESTABLISHED 26983/alpaca        
20260212_170225.587       4031  tcp        0      0 127.0.0.1:54212         127.0.0.1:8080          ESTABLISHED 26983/alpaca        
20260212_170225.587       4032  tcp        0      0 127.0.0.1:8080          127.0.0.1:41782         ESTABLISHED 26983/alpaca        
20260212_170225.587       4033  tcp        0      0 127.0.0.1:55846         127.0.0.1:8080          ESTABLISHED 26983/alpaca        
20260212_170225.587       4034  tcp6       0      0 ::1:8080                :::*                    LISTEN      26983/alpaca        
20260212_170225.587       4035  tcp6       0      0 ::1:8080                ::1:53072               ESTABLISHED 26983/alpaca        
20260212_170225.587       4036  tcp6       0      0 ::1:8080                ::1:50034               ESTABLISHED 26983/alpaca        
20260212_170225.587       4037  tcp6       0      0 ::1:8080                ::1:53098               ESTABLISHED 26983/alpaca        
20260212_170225.587       4038  tcp6       0      0 ::1:8080                ::1:40402               ESTABLISHED 26983/alpaca        
20260212_170225.587       4039  tcp6       0      0 ::1:8080                ::1:56916               ESTABLISHED 26983/alpaca        
20260212_170225.587       4040  tcp6       0      0 ::1:8080                ::1:59216               ESTABLISHED 26983/alpaca        
20260212_170225.587       4041  tcp6       0      0 ::1:8080                ::1:59204               ESTABLISHED 26983/alpaca        
20260212_170225.587       4042  tcp6       0      0 ::1:8080                ::1:56924               ESTABLISHED 26983/alpaca        
20260212_170225.587       4043  tcp6       0      0 ::1:8080                ::1:52984               ESTABLISHED 26983/alpaca        
20260212_170225.587       4044  tcp6       0      0 ::1:8080                ::1:50042               ESTABLISHED 26983/alpaca        
20260212_170225.587       4045  tcp6       0      0 ::1:8080                ::1:50040               ESTABLISHED 26983/alpaca        
20260212_170225.587       4046  tcp6       0      0 ::1:8080                ::1:50054               ESTABLISHED 26983/alpaca        

```

**Comment by samuong** [comment]
Hi @ferrieux, this sounds a bit different to the issue from 6 years ago. We were seeing a slow steady leak (one file descriptor per CONNECT request) that eventually crept up to the ulimit, whereas I think you're seeing Alpaca infinitely recurse while trying to proxy a request through itself? I've created another issue for this in #167, let's continue the discussion there.
